#!/bin/bash

ME=$(id -u)
if [ "$ME" = "0" ]; then
echo do not run this as root 
exit 
fi

ACCT=$(whoami)

DPBX=Dropbox
DESK="$HOME/.local/share/YTTS/bin"
ICON="$HOME/.local/share/YTTS/icons"

	echo -e "\e[1;33m Welcome to Your Trucking Trans Solutions.\e[0m"


if su -c true "$USER"; then
  echo -e "\e[1;31m Correct password\e[0m"
else
    echo -e "\e[1;31m sorry User Name or Password does not match\e[0m"
    echo -e "\e[1;31m check your spelling caps on ?\e[0m"
    sleep 5
    exit
fi

CWD=$(pwd)
rm form.txt
dialog --backtitle "Dialog Form Example" --title "Dialog - Form" \
--form "\nDialog Welcome YTTS setup $ACCT " 25 60 16 \
"1 git hub truck company name          1:" 1 1 "" 1 34 25 60 \
"2 git hub truck company URL           2:" 2 1 "" 2 34 25 60 \
"3 company abriviation                 3:" 3 1 "" 3 34 25 60 \
"4 company adress                      4:" 4 1 "" 4 25 25 60 \
"5 company phone nummber               5:" 5 1 "" 5 34 25 60 \
2>$CWD/form.txt

repcomin=$(sed -n 1p form.txt)
gitname=$(sed -n 2p form.txt)
coabriv=$(sed -n 3p form.txt)
address=$(sed -n 4p form.txt)
phone=$(sed -n 5p form.txt)
rm $CWD/form.txt


cat > sett <<EOF
sed -i 's/comin/$repcomin/g' YTTS-admin
sed -i 's/comin/$repcomin/g' YTTS-customer-sort
sed -i 's/comin/$repcomin/g' YTTS-payroll
sed -i 's/comin/$repcomin/g' YTTS-rsync
sed -i 's/comin/$repcomin/g' YTTS-sort
sed -i 's/yourabrv/$coabriv/g' YTTS-admin
sed -i 's/yourabrv/$coabriv/g' YTTS-sort
sed -i 's/comin/$repcomin/g' YTTS-split
sed -i 's/yourabrv/$coabriv/g' YTTS-split
sed -i 's|githubaddres|$gitname|g' YTTS-rsync
sed -i 's/ADDME/$address/g' YTTS-admin
sed -i 's/PHONME/$phone/g' YTTS-admin
EOF
sh sett
rm sett
cd $HOME/.local/share/applications
cat > dsett <<EOF
sed -i 's|Exec=|Exec=$DESK|g' YTTS-admin.desktop 
sed -i 's|Exec=|Exec=$DESK|g' YTTS-payroll.desktop 
sed -i 's|Exec=|Exec=$DESK|g' YTTS-rsync.desktop
sed -i 's|Exec=|Exec=$DESK|g' YTTS-setup.desktop  
sed -i 's|Exec=|Exec=$DESK|g' YTTS-sort.desktop 
sed -i 's|Exec=|Exec=$DESK|g' YTTS-split.desktop
sed -i 's|Exec=|Exec=$DESK|g' YTTS-customer-sort.desktop  
sed -i 's|Icon=|Icon=$ICON|g' YTTS-admin.desktop 
sed -i 's|Icon=|Icon=$ICON|g' YTTS-payroll.desktop 
sed -i 's|Icon=|Icon=$ICON|g' YTTS-rsync.desktop
sed -i 's|Icon=|Icon=$ICON|g' YTTS-setup.desktop  
sed -i 's|Icon=|Icon=$ICON|g' YTTS-sort.desktop 
sed -i 's|Icon=|Icon=$ICON|g' YTTS-split.desktop
sed -i 's|Icon=|Icon=$ICON|g' YTTS-customer-sort.desktop  
EOF
sh dsett
rm dsett
rm $CWD/form.txt

read -p 'Do you need to setup your dropbox Ready Y/N : ' decides
if [ "$decides" = "n" ]; then
   echo good day $ACCT
   exit
fi 
  
if [ "$decides" = "N" ]; then
   echo good day $ACCT
   exit
fi


mkdir -p $HOME/$DPBX/$gitlittle
cd $HOME/$DPBX/$gitlittle
mkdir Customers  Deactivated  Drivers  Monthly  Saftey Splits Trailers  Trucks  Weekly  Yearly
cd Deactivated 
mkdir Deactivated-Trailers Deactivated-Trucks Deactivated-Drivers
#

 
